[2025-04-06T18:55:40.235+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:51:21.234125+00:00 [queued]>
[2025-04-06T18:55:40.252+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:51:21.234125+00:00 [queued]>
[2025-04-06T18:55:40.253+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 4
[2025-04-06T18:55:40.276+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_data> on 2025-04-06 18:51:21.234125+00:00
[2025-04-06T18:55:40.291+0000] {standard_task_runner.py:57} INFO - Started process 4885 to run task
[2025-04-06T18:55:40.297+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'validate_data', 'manual__2025-04-06T18:51:21.234125+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmpclprrtr3']
[2025-04-06T18:55:40.298+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask validate_data
[2025-04-06T18:55:40.386+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:51:21.234125+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T18:55:40.532+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:51:21.234125+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:51:21.234125+00:00'
[2025-04-06T18:55:40.533+0000] {logging_mixin.py:150} INFO - üîç D√©marrage de la validation Great Expectations
[2025-04-06T18:55:40.534+0000] {logging_mixin.py:150} INFO - Connection string pour GE: postgresql://sportadvantagehr:sportpassword@business-postgres:5432/sportadvantages
[2025-04-06T18:55:40.537+0000] {util.py:2007} INFO - Could not find local context root directory
[2025-04-06T18:55:40.539+0000] {base.py:2134} INFO - Created temporary directory '/tmp/tmpx7j6ppfe' for ephemeral docs site
[2025-04-06T18:55:40.543+0000] {abstract_data_context.py:5575} INFO - EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`
[2025-04-06T18:55:40.545+0000] {config.py:185} INFO - Loading 'datasources' ->
[]
[2025-04-06T18:55:40.580+0000] {logging_mixin.py:150} INFO - ‚úÖ Contexte GE initialis√©
[2025-04-06T18:55:40.581+0000] {logging_mixin.py:150} INFO - Ajout de la source PostgreSQL...
[2025-04-06T18:55:40.659+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:55:40.690+0000] {logging_mixin.py:150} INFO - ‚úÖ Source PostgreSQL ajout√©e
[2025-04-06T18:55:40.691+0000] {logging_mixin.py:150} INFO - Connexion √† la base de donn√©es pour v√©rifier la table...
[2025-04-06T18:55:40.692+0000] {logging_mixin.py:150} INFO - Param√®tres de connexion GE: host=business-postgres, port=5432, user=sportadvantagehr, database=sportadvantages
[2025-04-06T18:55:40.702+0000] {logging_mixin.py:150} INFO - Sch√©mas disponibles: [('pg_toast',), ('pg_catalog',), ('public',), ('information_schema',), ('sport_advantages',), ('pg_temp_4',), ('pg_toast_temp_4',)]
[2025-04-06T18:55:40.703+0000] {logging_mixin.py:150} INFO - Le sch√©ma sport_advantages existe: True
[2025-04-06T18:55:40.706+0000] {logging_mixin.py:150} INFO - Tables dans le sch√©ma sport_advantages: [('employees',), ('commute_validations',), ('sport_activities',), ('sport_advantages',), ('employees_masked',)]
[2025-04-06T18:55:40.707+0000] {logging_mixin.py:150} INFO - La table sport_activities existe: True
[2025-04-06T18:55:40.713+0000] {logging_mixin.py:150} INFO - Colonnes de la table: [('id', 'integer'), ('id_employee', 'integer'), ('start_datetime', 'timestamp without time zone'), ('sport_type', 'character varying'), ('distance', 'integer'), ('activity_duration', 'integer'), ('comment', 'character varying')]
[2025-04-06T18:55:40.715+0000] {logging_mixin.py:150} INFO - Nombre de lignes dans la table: 2907
[2025-04-06T18:55:40.715+0000] {logging_mixin.py:150} INFO - √âchantillon de donn√©es: [(1, 70643, datetime.datetime(2024, 4, 5, 11, 0, 3), '√âquitation', None, 3918, None), (2, 34382, datetime.datetime(2024, 4, 5, 14, 45, 38), 'Musculation', None, 5035, None), (3, 50316, datetime.datetime(2024, 4, 5, 14, 40, 45), 'Judo', None, 3254, None), (4, 19773, datetime.datetime(2024, 4, 6, 19, 19, 24), 'Corde √† sauter', None, 5696, None), (5, 99401, datetime.datetime(2024, 4, 6, 10, 28, 43), 'Randonn√©e', 6770, 6449, None)]
[2025-04-06T18:55:40.716+0000] {logging_mixin.py:150} INFO - Ajout de l'asset de table...
[2025-04-06T18:55:40.728+0000] {logging_mixin.py:150} INFO - ‚úÖ Asset de table ajout√© avec succ√®s
[2025-04-06T18:55:40.729+0000] {logging_mixin.py:150} INFO - Construction de la requ√™te batch...
[2025-04-06T18:55:40.730+0000] {logging_mixin.py:150} INFO - ‚úÖ Requ√™te batch construite
[2025-04-06T18:55:40.730+0000] {logging_mixin.py:150} INFO - Configuration de la suite d'attente...
[2025-04-06T18:55:40.738+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente configur√©e
[2025-04-06T18:55:40.741+0000] {logging_mixin.py:150} INFO - Cr√©ation du validator...
[2025-04-06T18:55:40.744+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:55:40.766+0000] {batch_filter.py:250} INFO - batch_slice: None was parsed to: slice(0, None, None)
[2025-04-06T18:55:40.771+0000] {logging_mixin.py:150} INFO - ‚úÖ Validator cr√©√©
[2025-04-06T18:55:40.773+0000] {logging_mixin.py:150} INFO - Aper√ßu des donn√©es:
[2025-04-06T18:55:40.781+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:55:40.782+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:55:40.797+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 69.50it/s]
[2025-04-06T18:55:40.798+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 63.88it/s]
[2025-04-06T18:55:40.799+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 60.36it/s]
[2025-04-06T18:55:40.800+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 56.92it/s]
[2025-04-06T18:55:40.817+0000] {logging_mixin.py:150} INFO -    id  id_employee      start_datetime  ... distance  activity_duration  comment
0   1        70643 2024-04-05 11:00:03  ...      NaN               3918     None
1   2        34382 2024-04-05 14:45:38  ...      NaN               5035     None
2   3        50316 2024-04-05 14:40:45  ...      NaN               3254     None
3   4        19773 2024-04-06 19:19:24  ...      NaN               5696     None
4   5        99401 2024-04-06 10:28:43  ...   6770.0               6449     None

[5 rows x 7 columns]
[2025-04-06T18:55:40.818+0000] {logging_mixin.py:150} INFO - Ajout des attentes...
[2025-04-06T18:55:40.820+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/expectations/expectation.py:1464: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  UserWarning,

[2025-04-06T18:55:40.841+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:55:40.842+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:55:40.850+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 248.72it/s]
[2025-04-06T18:55:40.855+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 154.84it/s]
[2025-04-06T18:55:40.859+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 242.61it/s]
[2025-04-06T18:55:40.864+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 185.95it/s]
[2025-04-06T18:55:40.865+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 216.49it/s]
[2025-04-06T18:55:40.869+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 188.20it/s]
[2025-04-06T18:55:40.873+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 228.08it/s]
[2025-04-06T18:55:40.875+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 210.32it/s]
[2025-04-06T18:55:40.879+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 219.38it/s]
[2025-04-06T18:55:40.881+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 207.86it/s]
[2025-04-06T18:55:40.881+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 203.88it/s]
[2025-04-06T18:55:40.882+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 199.41it/s]
[2025-04-06T18:55:40.902+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:55:40.903+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:55:40.908+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 386.93it/s]
[2025-04-06T18:55:40.913+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 210.05it/s]
[2025-04-06T18:55:40.915+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 337.65it/s]
[2025-04-06T18:55:40.919+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 251.06it/s]
[2025-04-06T18:55:40.921+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 280.74it/s]
[2025-04-06T18:55:40.924+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 235.07it/s]
[2025-04-06T18:55:40.928+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 284.97it/s]
[2025-04-06T18:55:40.930+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 259.50it/s]
[2025-04-06T18:55:40.933+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 264.27it/s]
[2025-04-06T18:55:40.935+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 249.28it/s]
[2025-04-06T18:55:40.936+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 243.41it/s]
[2025-04-06T18:55:40.937+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 237.96it/s]
[2025-04-06T18:55:40.973+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:55:40.974+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:55:40.980+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 356.19it/s]
[2025-04-06T18:55:40.988+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 142.87it/s]
[2025-04-06T18:55:40.991+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 237.18it/s]
[2025-04-06T18:55:40.999+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 161.70it/s]
[2025-04-06T18:55:41.002+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 215.01it/s]
[2025-04-06T18:55:41.009+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 171.56it/s]
[2025-04-06T18:55:41.014+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 223.40it/s]
[2025-04-06T18:55:41.019+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 201.02it/s]
[2025-04-06T18:55:41.024+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 220.69it/s]
[2025-04-06T18:55:41.027+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 206.63it/s]
[2025-04-06T18:55:41.028+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 203.59it/s]
[2025-04-06T18:55:41.029+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 200.50it/s]
[2025-04-06T18:55:41.065+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:55:41.066+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:55:41.071+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 351.40it/s]
[2025-04-06T18:55:41.079+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 146.34it/s]
[2025-04-06T18:55:41.082+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 243.38it/s]
[2025-04-06T18:55:41.090+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 163.57it/s]
[2025-04-06T18:55:41.093+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 220.09it/s]
[2025-04-06T18:55:41.099+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 179.15it/s]
[2025-04-06T18:55:41.105+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 228.94it/s]
[2025-04-06T18:55:41.109+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 206.00it/s]
[2025-04-06T18:55:41.114+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 227.52it/s]
[2025-04-06T18:55:41.117+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 213.75it/s]
[2025-04-06T18:55:41.118+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 211.24it/s]
[2025-04-06T18:55:41.118+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 208.76it/s]
[2025-04-06T18:55:41.124+0000] {logging_mixin.py:150} INFO - ‚úÖ Attentes ajout√©es
[2025-04-06T18:55:41.125+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:55:41.126+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:55:41.132+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:55:41.134+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:55:41.135+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:55:41.141+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:55:41.142+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation...
[2025-04-06T18:55:41.144+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation avec SimpleCheckpoint...
[2025-04-06T18:55:41.149+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 51, in _get
    return self._store[key]
KeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 145, in get_checkpoint
    checkpoint_config: Optional[Any] = self.get(key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 188, in get
    value = self._store_backend.get(self.key_to_tuple(key))
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 121, in get
    value = self._get(key, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 53, in _get
    raise InvalidKeyError(f"{str(e)}")
great_expectations.exceptions.exceptions.InvalidKeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_validation_dag.py", line 346, in run_ge_validation
    run_name="airflow_validation_run"
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2288, in run_checkpoint
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2313, in _run_checkpoint
    id=id,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2163, in get_checkpoint
    name=name, id=id
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 151, in get_checkpoint
    message=f'Non-existent Checkpoint configuration named "{key.configuration_key}".\n\nDetails: {exc_ik}'  # type: ignore[union-attr]
great_expectations.exceptions.exceptions.CheckpointNotFoundError: Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',)
[2025-04-06T18:55:41.168+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=great_expectations_validation, task_id=validate_data, execution_date=20250406T185121, start_date=20250406T185540, end_date=20250406T185541
[2025-04-06T18:55:41.181+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 25 for task validate_data (Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',); 4885)
[2025-04-06T18:55:41.232+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-06T18:55:41.267+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
