[2025-04-06T18:57:46.544+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:51:21.234125+00:00 [queued]>
[2025-04-06T18:57:46.558+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:51:21.234125+00:00 [queued]>
[2025-04-06T18:57:46.559+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2025-04-06T18:57:46.594+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_data> on 2025-04-06 18:51:21.234125+00:00
[2025-04-06T18:57:46.604+0000] {standard_task_runner.py:57} INFO - Started process 4977 to run task
[2025-04-06T18:57:46.612+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'validate_data', 'manual__2025-04-06T18:51:21.234125+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmp3ujer6dr']
[2025-04-06T18:57:46.615+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask validate_data
[2025-04-06T18:57:46.714+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:51:21.234125+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T18:57:46.863+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:51:21.234125+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:51:21.234125+00:00'
[2025-04-06T18:57:46.864+0000] {logging_mixin.py:150} INFO - üîç D√©marrage de la validation Great Expectations
[2025-04-06T18:57:46.866+0000] {logging_mixin.py:150} INFO - Connection string pour GE: postgresql://sportadvantagehr:sportpassword@business-postgres:5432/sportadvantages
[2025-04-06T18:57:46.869+0000] {util.py:2007} INFO - Could not find local context root directory
[2025-04-06T18:57:46.874+0000] {base.py:2134} INFO - Created temporary directory '/tmp/tmpuailljp4' for ephemeral docs site
[2025-04-06T18:57:46.878+0000] {abstract_data_context.py:5575} INFO - EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`
[2025-04-06T18:57:46.879+0000] {config.py:185} INFO - Loading 'datasources' ->
[]
[2025-04-06T18:57:46.915+0000] {logging_mixin.py:150} INFO - ‚úÖ Contexte GE initialis√©
[2025-04-06T18:57:46.917+0000] {logging_mixin.py:150} INFO - Ajout de la source PostgreSQL...
[2025-04-06T18:57:47.004+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:57:47.042+0000] {logging_mixin.py:150} INFO - ‚úÖ Source PostgreSQL ajout√©e
[2025-04-06T18:57:47.044+0000] {logging_mixin.py:150} INFO - Connexion √† la base de donn√©es pour v√©rifier la table...
[2025-04-06T18:57:47.045+0000] {logging_mixin.py:150} INFO - Param√®tres de connexion GE: host=business-postgres, port=5432, user=sportadvantagehr, database=sportadvantages
[2025-04-06T18:57:47.057+0000] {logging_mixin.py:150} INFO - Sch√©mas disponibles: [('pg_toast',), ('pg_catalog',), ('public',), ('information_schema',), ('sport_advantages',), ('pg_temp_4',), ('pg_toast_temp_4',)]
[2025-04-06T18:57:47.058+0000] {logging_mixin.py:150} INFO - Le sch√©ma sport_advantages existe: True
[2025-04-06T18:57:47.061+0000] {logging_mixin.py:150} INFO - Tables dans le sch√©ma sport_advantages: [('employees',), ('commute_validations',), ('sport_activities',), ('sport_advantages',), ('employees_masked',)]
[2025-04-06T18:57:47.062+0000] {logging_mixin.py:150} INFO - La table sport_activities existe: True
[2025-04-06T18:57:47.067+0000] {logging_mixin.py:150} INFO - Colonnes de la table: [('id', 'integer'), ('id_employee', 'integer'), ('start_datetime', 'timestamp without time zone'), ('sport_type', 'character varying'), ('distance', 'integer'), ('activity_duration', 'integer'), ('comment', 'character varying')]
[2025-04-06T18:57:47.069+0000] {logging_mixin.py:150} INFO - Nombre de lignes dans la table: 2907
[2025-04-06T18:57:47.071+0000] {logging_mixin.py:150} INFO - √âchantillon de donn√©es: [(1, 70643, datetime.datetime(2024, 4, 5, 11, 0, 3), '√âquitation', None, 3918, None), (2, 34382, datetime.datetime(2024, 4, 5, 14, 45, 38), 'Musculation', None, 5035, None), (3, 50316, datetime.datetime(2024, 4, 5, 14, 40, 45), 'Judo', None, 3254, None), (4, 19773, datetime.datetime(2024, 4, 6, 19, 19, 24), 'Corde √† sauter', None, 5696, None), (5, 99401, datetime.datetime(2024, 4, 6, 10, 28, 43), 'Randonn√©e', 6770, 6449, None)]
[2025-04-06T18:57:47.072+0000] {logging_mixin.py:150} INFO - Ajout de l'asset de table...
[2025-04-06T18:57:47.087+0000] {logging_mixin.py:150} INFO - ‚úÖ Asset de table ajout√© avec succ√®s
[2025-04-06T18:57:47.088+0000] {logging_mixin.py:150} INFO - Construction de la requ√™te batch...
[2025-04-06T18:57:47.089+0000] {logging_mixin.py:150} INFO - ‚úÖ Requ√™te batch construite
[2025-04-06T18:57:47.090+0000] {logging_mixin.py:150} INFO - Configuration de la suite d'attente...
[2025-04-06T18:57:47.099+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente configur√©e
[2025-04-06T18:57:47.103+0000] {logging_mixin.py:150} INFO - Cr√©ation du validator...
[2025-04-06T18:57:47.107+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:57:47.157+0000] {batch_filter.py:250} INFO - batch_slice: None was parsed to: slice(0, None, None)
[2025-04-06T18:57:47.163+0000] {logging_mixin.py:150} INFO - ‚úÖ Validator cr√©√©
[2025-04-06T18:57:47.165+0000] {logging_mixin.py:150} INFO - Aper√ßu des donn√©es:
[2025-04-06T18:57:47.178+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:57:47.179+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:57:47.194+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 66.19it/s]
[2025-04-06T18:57:47.196+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 60.66it/s]
[2025-04-06T18:57:47.197+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 57.32it/s]
[2025-04-06T18:57:47.198+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 54.52it/s]
[2025-04-06T18:57:47.224+0000] {logging_mixin.py:150} INFO -    id  id_employee      start_datetime  ... distance  activity_duration  comment
0   1        70643 2024-04-05 11:00:03  ...      NaN               3918     None
1   2        34382 2024-04-05 14:45:38  ...      NaN               5035     None
2   3        50316 2024-04-05 14:40:45  ...      NaN               3254     None
3   4        19773 2024-04-06 19:19:24  ...      NaN               5696     None
4   5        99401 2024-04-06 10:28:43  ...   6770.0               6449     None

[5 rows x 7 columns]
[2025-04-06T18:57:47.225+0000] {logging_mixin.py:150} INFO - Ajout des attentes...
[2025-04-06T18:57:47.228+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/expectations/expectation.py:1464: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  UserWarning,

[2025-04-06T18:57:47.251+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:57:47.252+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:57:47.262+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 189.23it/s]
[2025-04-06T18:57:47.269+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 117.42it/s]
[2025-04-06T18:57:47.275+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 173.36it/s]
[2025-04-06T18:57:47.281+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 136.12it/s]
[2025-04-06T18:57:47.283+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 158.79it/s]
[2025-04-06T18:57:47.287+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 141.91it/s]
[2025-04-06T18:57:47.291+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 179.23it/s]
[2025-04-06T18:57:47.294+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 165.07it/s]
[2025-04-06T18:57:47.298+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 174.15it/s]
[2025-04-06T18:57:47.300+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 166.08it/s]
[2025-04-06T18:57:47.301+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 162.98it/s]
[2025-04-06T18:57:47.301+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 160.73it/s]
[2025-04-06T18:57:47.323+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:57:47.325+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:57:47.332+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 281.41it/s]
[2025-04-06T18:57:47.336+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 169.07it/s]
[2025-04-06T18:57:47.339+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 271.23it/s]
[2025-04-06T18:57:47.344+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 207.95it/s]
[2025-04-06T18:57:47.345+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 238.56it/s]
[2025-04-06T18:57:47.349+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 200.33it/s]
[2025-04-06T18:57:47.353+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 243.11it/s]
[2025-04-06T18:57:47.356+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 222.69it/s]
[2025-04-06T18:57:47.360+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 227.00it/s]
[2025-04-06T18:57:47.362+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 213.06it/s]
[2025-04-06T18:57:47.363+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 208.99it/s]
[2025-04-06T18:57:47.364+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 204.83it/s]
[2025-04-06T18:57:47.403+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:57:47.405+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:57:47.411+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 292.09it/s]
[2025-04-06T18:57:47.421+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 119.72it/s]
[2025-04-06T18:57:47.425+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 192.17it/s]
[2025-04-06T18:57:47.435+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 131.43it/s]
[2025-04-06T18:57:47.438+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 176.97it/s]
[2025-04-06T18:57:47.448+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 138.18it/s]
[2025-04-06T18:57:47.454+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 180.17it/s]
[2025-04-06T18:57:47.459+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 164.09it/s]
[2025-04-06T18:57:47.465+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 180.64it/s]
[2025-04-06T18:57:47.470+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 168.50it/s]
[2025-04-06T18:57:47.471+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 165.05it/s]
[2025-04-06T18:57:47.472+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 161.94it/s]
[2025-04-06T18:57:47.516+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:57:47.518+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:57:47.527+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 214.64it/s]
[2025-04-06T18:57:47.536+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 107.46it/s]
[2025-04-06T18:57:47.539+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 182.35it/s]
[2025-04-06T18:57:47.548+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 133.11it/s]
[2025-04-06T18:57:47.551+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 181.53it/s]
[2025-04-06T18:57:47.561+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 139.13it/s]
[2025-04-06T18:57:47.567+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 183.25it/s]
[2025-04-06T18:57:47.574+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 159.58it/s]
[2025-04-06T18:57:47.582+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 171.89it/s]
[2025-04-06T18:57:47.586+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 161.67it/s]
[2025-04-06T18:57:47.587+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 159.41it/s]
[2025-04-06T18:57:47.588+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 156.95it/s]
[2025-04-06T18:57:47.594+0000] {logging_mixin.py:150} INFO - ‚úÖ Attentes ajout√©es
[2025-04-06T18:57:47.595+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:57:47.597+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:57:47.603+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:57:47.606+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:57:47.608+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:57:47.619+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:57:47.623+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation...
[2025-04-06T18:57:47.625+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation avec SimpleCheckpoint...
[2025-04-06T18:57:47.635+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 51, in _get
    return self._store[key]
KeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 145, in get_checkpoint
    checkpoint_config: Optional[Any] = self.get(key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 188, in get
    value = self._store_backend.get(self.key_to_tuple(key))
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 121, in get
    value = self._get(key, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 53, in _get
    raise InvalidKeyError(f"{str(e)}")
great_expectations.exceptions.exceptions.InvalidKeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_validation_dag.py", line 346, in run_ge_validation
    run_name="airflow_validation_run"
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2288, in run_checkpoint
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2313, in _run_checkpoint
    id=id,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2163, in get_checkpoint
    name=name, id=id
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 151, in get_checkpoint
    message=f'Non-existent Checkpoint configuration named "{key.configuration_key}".\n\nDetails: {exc_ik}'  # type: ignore[union-attr]
great_expectations.exceptions.exceptions.CheckpointNotFoundError: Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',)
[2025-04-06T18:57:47.658+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=great_expectations_validation, task_id=validate_data, execution_date=20250406T185121, start_date=20250406T185746, end_date=20250406T185747
[2025-04-06T18:57:47.677+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 26 for task validate_data (Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',); 4977)
[2025-04-06T18:57:47.707+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-06T18:57:47.742+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
