[2025-04-06T18:41:47.394+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.check_table_exists manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:41:47.411+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.check_table_exists manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:41:47.413+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-04-06T18:41:47.444+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_table_exists> on 2025-04-06 18:41:41.055095+00:00
[2025-04-06T18:41:47.465+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'check_table_exists', 'manual__2025-04-06T18:41:41.055095+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmpkiqggcvj']
[2025-04-06T18:41:47.461+0000] {standard_task_runner.py:57} INFO - Started process 4257 to run task
[2025-04-06T18:41:47.469+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask check_table_exists
[2025-04-06T18:41:47.826+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.check_table_exists manual__2025-04-06T18:41:41.055095+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T18:41:48.501+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='check_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:41:41.055095+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:41:41.055095+00:00'
[2025-04-06T18:41:48.506+0000] {logging_mixin.py:150} INFO - Connexion string vérifiée: postgresql://sportadvantagehr:sportpassword@business-postgres:5432/sportadvantages
[2025-04-06T18:41:48.509+0000] {logging_mixin.py:150} INFO - Paramètres de connexion: host=business-postgres, port=5432, user=sportadvantagehr, database=sportadvantages
[2025-04-06T18:41:48.510+0000] {logging_mixin.py:150} INFO - Tentative de connexion 1/5
[2025-04-06T18:41:48.522+0000] {logging_mixin.py:150} INFO - Connexion réussie!
[2025-04-06T18:41:48.524+0000] {logging_mixin.py:150} INFO - Exécution de la requête: SELECT schema_name FROM information_schema.schemata;
[2025-04-06T18:41:48.527+0000] {logging_mixin.py:150} INFO - Tous les schémas disponibles: [('pg_toast',), ('pg_catalog',), ('public',), ('information_schema',), ('sport_advantages',), ('pg_temp_4',), ('pg_toast_temp_4',)]
[2025-04-06T18:41:48.529+0000] {logging_mixin.py:150} INFO - Exécution de la requête: SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'sport_advantages';
[2025-04-06T18:41:48.532+0000] {logging_mixin.py:150} INFO - Schéma sport_advantages: [('sport_advantages',)]
[2025-04-06T18:41:48.537+0000] {logging_mixin.py:150} INFO - Exécution de la requête: SELECT table_name FROM information_schema.tables WHERE table_schema = 'sport_advantages';
[2025-04-06T18:41:48.544+0000] {logging_mixin.py:150} INFO - Toutes les tables dans le schéma sport_advantages: [('employees',), ('commute_validations',), ('sport_activities',), ('sport_advantages',), ('employees_masked',)]
[2025-04-06T18:41:48.612+0000] {logging_mixin.py:150} INFO - Exécution de la requête: 
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'sport_advantages' 
                AND table_name = 'sport_activities';
                
[2025-04-06T18:41:48.615+0000] {logging_mixin.py:150} INFO - Table sport_activities: [('sport_activities',)]
[2025-04-06T18:41:48.618+0000] {logging_mixin.py:150} INFO - ✅ La table 'sport_advantages.sport_activities' existe!
[2025-04-06T18:41:48.625+0000] {logging_mixin.py:150} INFO - Exécution de la requête: SELECT * FROM sport_advantages.sport_activities LIMIT 5;
[2025-04-06T18:41:48.650+0000] {logging_mixin.py:150} INFO - Échantillon de données: [(1, 70643, datetime.datetime(2024, 4, 5, 11, 0, 3), 'Équitation', None, 3918, None), (2, 34382, datetime.datetime(2024, 4, 5, 14, 45, 38), 'Musculation', None, 5035, None), (3, 50316, datetime.datetime(2024, 4, 5, 14, 40, 45), 'Judo', None, 3254, None), (4, 19773, datetime.datetime(2024, 4, 6, 19, 19, 24), 'Corde à sauter', None, 5696, None), (5, 99401, datetime.datetime(2024, 4, 6, 10, 28, 43), 'Randonnée', 6770, 6449, None)]
[2025-04-06T18:41:48.667+0000] {logging_mixin.py:150} INFO - Connexion fermée
[2025-04-06T18:41:48.670+0000] {python.py:183} INFO - Done. Returned value was: True
[2025-04-06T18:41:48.808+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=great_expectations_validation, task_id=check_table_exists, execution_date=20250406T184141, start_date=20250406T184147, end_date=20250406T184148
[2025-04-06T18:41:48.899+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-04-06T18:41:48.984+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
