[2025-04-06T17:13:12.328+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.check_table_exists manual__2025-04-06T17:12:59.632075+00:00 [queued]>
[2025-04-06T17:13:12.346+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.check_table_exists manual__2025-04-06T17:12:59.632075+00:00 [queued]>
[2025-04-06T17:13:12.347+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 4
[2025-04-06T17:13:12.372+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_table_exists> on 2025-04-06 17:12:59.632075+00:00
[2025-04-06T17:13:12.395+0000] {standard_task_runner.py:57} INFO - Started process 738 to run task
[2025-04-06T17:13:12.409+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'check_table_exists', 'manual__2025-04-06T17:12:59.632075+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmpmweo4777']
[2025-04-06T17:13:12.413+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask check_table_exists
[2025-04-06T17:13:12.557+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.check_table_exists manual__2025-04-06T17:12:59.632075+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T17:13:12.748+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='check_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T17:12:59.632075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T17:12:59.632075+00:00'
[2025-04-06T17:13:12.819+0000] {logging_mixin.py:150} INFO - La table 'sport_advantages.sport_activities' existe!
[2025-04-06T17:13:12.820+0000] {python.py:183} INFO - Done. Returned value was: True
[2025-04-06T17:13:12.862+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=great_expectations_validation, task_id=check_table_exists, execution_date=20250406T171259, start_date=20250406T171312, end_date=20250406T171312
[2025-04-06T17:13:12.936+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-04-06T17:13:13.117+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
