[2025-04-06T18:48:15.247+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:48:15.261+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:48:15.263+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2025-04-06T18:48:15.284+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_data> on 2025-04-06 18:41:41.055095+00:00
[2025-04-06T18:48:15.295+0000] {standard_task_runner.py:57} INFO - Started process 4538 to run task
[2025-04-06T18:48:15.301+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'validate_data', 'manual__2025-04-06T18:41:41.055095+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmpap3_05jw']
[2025-04-06T18:48:15.304+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask validate_data
[2025-04-06T18:48:15.397+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T18:48:16.609+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:41:41.055095+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:41:41.055095+00:00'
[2025-04-06T18:48:16.613+0000] {logging_mixin.py:150} INFO - üîç D√©marrage de la validation Great Expectations
[2025-04-06T18:48:16.615+0000] {logging_mixin.py:150} INFO - Connection string pour GE: postgresql://sportadvantagehr:sportpassword@business-postgres:5432/sportadvantages
[2025-04-06T18:48:16.621+0000] {util.py:2007} INFO - Could not find local context root directory
[2025-04-06T18:48:16.624+0000] {base.py:2134} INFO - Created temporary directory '/tmp/tmpih7tp4wu' for ephemeral docs site
[2025-04-06T18:48:16.629+0000] {abstract_data_context.py:5575} INFO - EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`
[2025-04-06T18:48:16.631+0000] {config.py:185} INFO - Loading 'datasources' ->
[]
[2025-04-06T18:48:16.691+0000] {logging_mixin.py:150} INFO - ‚úÖ Contexte GE initialis√©
[2025-04-06T18:48:16.693+0000] {logging_mixin.py:150} INFO - Ajout de la source PostgreSQL...
[2025-04-06T18:48:16.811+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:48:16.856+0000] {logging_mixin.py:150} INFO - ‚úÖ Source PostgreSQL ajout√©e
[2025-04-06T18:48:16.858+0000] {logging_mixin.py:150} INFO - Connexion √† la base de donn√©es pour v√©rifier la table...
[2025-04-06T18:48:16.859+0000] {logging_mixin.py:150} INFO - Param√®tres de connexion GE: host=business-postgres, port=5432, user=sportadvantagehr, database=sportadvantages
[2025-04-06T18:48:16.872+0000] {logging_mixin.py:150} INFO - Sch√©mas disponibles: [('pg_toast',), ('pg_catalog',), ('public',), ('information_schema',), ('sport_advantages',), ('pg_temp_4',), ('pg_toast_temp_4',)]
[2025-04-06T18:48:16.874+0000] {logging_mixin.py:150} INFO - Le sch√©ma sport_advantages existe: True
[2025-04-06T18:48:16.878+0000] {logging_mixin.py:150} INFO - Tables dans le sch√©ma sport_advantages: [('employees',), ('commute_validations',), ('sport_activities',), ('sport_advantages',), ('employees_masked',)]
[2025-04-06T18:48:16.882+0000] {logging_mixin.py:150} INFO - La table sport_activities existe: True
[2025-04-06T18:48:16.891+0000] {logging_mixin.py:150} INFO - Colonnes de la table: [('id', 'integer'), ('id_employee', 'integer'), ('start_datetime', 'timestamp without time zone'), ('sport_type', 'character varying'), ('distance', 'integer'), ('activity_duration', 'integer'), ('comment', 'character varying')]
[2025-04-06T18:48:16.894+0000] {logging_mixin.py:150} INFO - Nombre de lignes dans la table: 2907
[2025-04-06T18:48:16.896+0000] {logging_mixin.py:150} INFO - √âchantillon de donn√©es: [(1, 70643, datetime.datetime(2024, 4, 5, 11, 0, 3), '√âquitation', None, 3918, None), (2, 34382, datetime.datetime(2024, 4, 5, 14, 45, 38), 'Musculation', None, 5035, None), (3, 50316, datetime.datetime(2024, 4, 5, 14, 40, 45), 'Judo', None, 3254, None), (4, 19773, datetime.datetime(2024, 4, 6, 19, 19, 24), 'Corde √† sauter', None, 5696, None), (5, 99401, datetime.datetime(2024, 4, 6, 10, 28, 43), 'Randonn√©e', 6770, 6449, None)]
[2025-04-06T18:48:16.898+0000] {logging_mixin.py:150} INFO - Ajout de l'asset de table...
[2025-04-06T18:48:16.915+0000] {logging_mixin.py:150} INFO - ‚úÖ Asset de table ajout√© avec succ√®s
[2025-04-06T18:48:16.918+0000] {logging_mixin.py:150} INFO - Construction de la requ√™te batch...
[2025-04-06T18:48:16.920+0000] {logging_mixin.py:150} INFO - ‚úÖ Requ√™te batch construite
[2025-04-06T18:48:16.921+0000] {logging_mixin.py:150} INFO - Configuration de la suite d'attente...
[2025-04-06T18:48:16.932+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente configur√©e
[2025-04-06T18:48:16.936+0000] {logging_mixin.py:150} INFO - Cr√©ation du validator...
[2025-04-06T18:48:16.941+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:48:16.978+0000] {batch_filter.py:250} INFO - batch_slice: None was parsed to: slice(0, None, None)
[2025-04-06T18:48:16.986+0000] {logging_mixin.py:150} INFO - ‚úÖ Validator cr√©√©
[2025-04-06T18:48:16.990+0000] {logging_mixin.py:150} INFO - Aper√ßu des donn√©es:
[2025-04-06T18:48:17.002+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:48:17.003+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:48:17.023+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 51.32it/s]
[2025-04-06T18:48:17.025+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 45.45it/s]
[2025-04-06T18:48:17.026+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 43.29it/s]
[2025-04-06T18:48:17.027+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 41.30it/s]
[2025-04-06T18:48:17.053+0000] {logging_mixin.py:150} INFO -    id  id_employee      start_datetime  ... distance  activity_duration  comment
0   1        70643 2024-04-05 11:00:03  ...      NaN               3918     None
1   2        34382 2024-04-05 14:45:38  ...      NaN               5035     None
2   3        50316 2024-04-05 14:40:45  ...      NaN               3254     None
3   4        19773 2024-04-06 19:19:24  ...      NaN               5696     None
4   5        99401 2024-04-06 10:28:43  ...   6770.0               6449     None

[5 rows x 7 columns]
[2025-04-06T18:48:17.054+0000] {logging_mixin.py:150} INFO - Ajout des attentes...
[2025-04-06T18:48:17.058+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/expectations/expectation.py:1464: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  UserWarning,

[2025-04-06T18:48:17.086+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:48:17.089+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:48:17.106+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 111.80it/s]
[2025-04-06T18:48:17.113+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 79.79it/s] 
[2025-04-06T18:48:17.120+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 126.07it/s]
[2025-04-06T18:48:17.128+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 102.23it/s]
[2025-04-06T18:48:17.130+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 119.52it/s]
[2025-04-06T18:48:17.135+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 106.79it/s]
[2025-04-06T18:48:17.143+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 128.26it/s]
[2025-04-06T18:48:17.147+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 120.16it/s]
[2025-04-06T18:48:17.152+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 126.17it/s]
[2025-04-06T18:48:17.155+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 120.63it/s]
[2025-04-06T18:48:17.156+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 118.71it/s]
[2025-04-06T18:48:17.157+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 116.63it/s]
[2025-04-06T18:48:17.187+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:48:17.189+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:48:17.196+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 270.57it/s]
[2025-04-06T18:48:17.203+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 141.70it/s]
[2025-04-06T18:48:17.207+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 221.27it/s]
[2025-04-06T18:48:17.213+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 164.76it/s]
[2025-04-06T18:48:17.216+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 185.74it/s]
[2025-04-06T18:48:17.222+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 151.68it/s]
[2025-04-06T18:48:17.228+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 180.87it/s]
[2025-04-06T18:48:17.231+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 165.22it/s]
[2025-04-06T18:48:17.237+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 167.66it/s]
[2025-04-06T18:48:17.240+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 155.64it/s]
[2025-04-06T18:48:17.242+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 151.22it/s]
[2025-04-06T18:48:17.243+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 148.04it/s]
[2025-04-06T18:48:17.346+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:48:17.349+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:48:17.374+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 78.78it/s]
[2025-04-06T18:48:17.410+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 32.61it/s]
[2025-04-06T18:48:17.417+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 58.57it/s]
[2025-04-06T18:48:17.432+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 48.38it/s]
[2025-04-06T18:48:17.439+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 66.50it/s]
[2025-04-06T18:48:17.451+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.455+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.464+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.474+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.483+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.494+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.496+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 58.83it/s]
[2025-04-06T18:48:17.497+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 74.01it/s]
[2025-04-06T18:48:17.553+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:48:17.556+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:48:17.564+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 229.18it/s]
[2025-04-06T18:48:17.578+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 88.28it/s] 
[2025-04-06T18:48:17.583+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 148.02it/s]
[2025-04-06T18:48:17.598+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 94.55it/s] 
[2025-04-06T18:48:17.606+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 118.85it/s]
[2025-04-06T18:48:17.647+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 65.57it/s] 
[2025-04-06T18:48:17.673+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 76.47it/s]
[2025-04-06T18:48:17.676+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 76.47it/s]
[2025-04-06T18:48:17.691+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 76.47it/s]
[2025-04-06T18:48:17.709+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 76.47it/s]
[2025-04-06T18:48:17.720+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 76.47it/s]
[2025-04-06T18:48:17.722+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 76.47it/s]
[2025-04-06T18:48:17.723+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 65.53it/s]
[2025-04-06T18:48:17.735+0000] {logging_mixin.py:150} INFO - ‚úÖ Attentes ajout√©es
[2025-04-06T18:48:17.736+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:48:17.740+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:48:17.752+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:48:17.756+0000] {logging_mixin.py:150} INFO - Cr√©ation du checkpoint...
[2025-04-06T18:48:17.758+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:48:17.760+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:48:17.778+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:48:17.781+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation...
[2025-04-06T18:48:17.783+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation avec SimpleCheckpoint...
[2025-04-06T18:48:17.794+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 51, in _get
    return self._store[key]
KeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 145, in get_checkpoint
    checkpoint_config: Optional[Any] = self.get(key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 188, in get
    value = self._store_backend.get(self.key_to_tuple(key))
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 121, in get
    value = self._get(key, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 53, in _get
    raise InvalidKeyError(f"{str(e)}")
great_expectations.exceptions.exceptions.InvalidKeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_validation_dag.py", line 351, in run_ge_validation
    run_name="airflow_validation_run"
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2288, in run_checkpoint
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2313, in _run_checkpoint
    id=id,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2163, in get_checkpoint
    name=name, id=id
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 151, in get_checkpoint
    message=f'Non-existent Checkpoint configuration named "{key.configuration_key}".\n\nDetails: {exc_ik}'  # type: ignore[union-attr]
great_expectations.exceptions.exceptions.CheckpointNotFoundError: Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',)
[2025-04-06T18:48:17.828+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=great_expectations_validation, task_id=validate_data, execution_date=20250406T184141, start_date=20250406T184815, end_date=20250406T184817
[2025-04-06T18:48:17.849+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 21 for task validate_data (Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',); 4538)
[2025-04-06T18:48:17.931+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-06T18:48:17.984+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
