[2025-04-06T18:44:00.132+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:44:00.170+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:44:00.172+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 4
[2025-04-06T18:44:00.227+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_data> on 2025-04-06 18:41:41.055095+00:00
[2025-04-06T18:44:00.242+0000] {standard_task_runner.py:57} INFO - Started process 4360 to run task
[2025-04-06T18:44:00.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'validate_data', 'manual__2025-04-06T18:41:41.055095+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmpn9ncp6_s']
[2025-04-06T18:44:00.251+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask validate_data
[2025-04-06T18:44:00.356+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T18:44:00.631+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:41:41.055095+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:41:41.055095+00:00'
[2025-04-06T18:44:00.644+0000] {logging_mixin.py:150} INFO - üîç D√©marrage de la validation Great Expectations
[2025-04-06T18:44:00.645+0000] {logging_mixin.py:150} INFO - Connection string pour GE: postgresql://sportadvantagehr:sportpassword@business-postgres:5432/sportadvantages
[2025-04-06T18:44:00.666+0000] {util.py:2007} INFO - Could not find local context root directory
[2025-04-06T18:44:00.681+0000] {base.py:2134} INFO - Created temporary directory '/tmp/tmp1j5_qn6s' for ephemeral docs site
[2025-04-06T18:44:00.710+0000] {abstract_data_context.py:5575} INFO - EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`
[2025-04-06T18:44:00.711+0000] {config.py:185} INFO - Loading 'datasources' ->
[]
[2025-04-06T18:44:00.753+0000] {logging_mixin.py:150} INFO - ‚úÖ Contexte GE initialis√©
[2025-04-06T18:44:00.754+0000] {logging_mixin.py:150} INFO - Ajout de la source PostgreSQL...
[2025-04-06T18:44:00.849+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:44:00.888+0000] {logging_mixin.py:150} INFO - ‚úÖ Source PostgreSQL ajout√©e
[2025-04-06T18:44:00.889+0000] {logging_mixin.py:150} INFO - Connexion √† la base de donn√©es pour v√©rifier la table...
[2025-04-06T18:44:00.890+0000] {logging_mixin.py:150} INFO - Param√®tres de connexion GE: host=business-postgres, port=5432, user=sportadvantagehr, database=sportadvantages
[2025-04-06T18:44:00.904+0000] {logging_mixin.py:150} INFO - Sch√©mas disponibles: [('pg_toast',), ('pg_catalog',), ('public',), ('information_schema',), ('sport_advantages',), ('pg_temp_4',), ('pg_toast_temp_4',)]
[2025-04-06T18:44:00.905+0000] {logging_mixin.py:150} INFO - Le sch√©ma sport_advantages existe: True
[2025-04-06T18:44:00.909+0000] {logging_mixin.py:150} INFO - Tables dans le sch√©ma sport_advantages: [('employees',), ('commute_validations',), ('sport_activities',), ('sport_advantages',), ('employees_masked',)]
[2025-04-06T18:44:00.911+0000] {logging_mixin.py:150} INFO - La table sport_activities existe: True
[2025-04-06T18:44:00.925+0000] {logging_mixin.py:150} INFO - Colonnes de la table: [('id', 'integer'), ('id_employee', 'integer'), ('start_datetime', 'timestamp without time zone'), ('sport_type', 'character varying'), ('distance', 'integer'), ('activity_duration', 'integer'), ('comment', 'character varying')]
[2025-04-06T18:44:00.928+0000] {logging_mixin.py:150} INFO - Nombre de lignes dans la table: 2907
[2025-04-06T18:44:00.930+0000] {logging_mixin.py:150} INFO - √âchantillon de donn√©es: [(1, 70643, datetime.datetime(2024, 4, 5, 11, 0, 3), '√âquitation', None, 3918, None), (2, 34382, datetime.datetime(2024, 4, 5, 14, 45, 38), 'Musculation', None, 5035, None), (3, 50316, datetime.datetime(2024, 4, 5, 14, 40, 45), 'Judo', None, 3254, None), (4, 19773, datetime.datetime(2024, 4, 6, 19, 19, 24), 'Corde √† sauter', None, 5696, None), (5, 99401, datetime.datetime(2024, 4, 6, 10, 28, 43), 'Randonn√©e', 6770, 6449, None)]
[2025-04-06T18:44:00.932+0000] {logging_mixin.py:150} INFO - Ajout de l'asset de table...
[2025-04-06T18:44:00.954+0000] {logging_mixin.py:150} INFO - ‚úÖ Asset de table ajout√© avec succ√®s
[2025-04-06T18:44:00.956+0000] {logging_mixin.py:150} INFO - Construction de la requ√™te batch...
[2025-04-06T18:44:00.957+0000] {logging_mixin.py:150} INFO - ‚úÖ Requ√™te batch construite
[2025-04-06T18:44:00.958+0000] {logging_mixin.py:150} INFO - Configuration de la suite d'attente...
[2025-04-06T18:44:00.969+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente configur√©e
[2025-04-06T18:44:00.973+0000] {logging_mixin.py:150} INFO - Cr√©ation du validator...
[2025-04-06T18:44:00.982+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:44:01.106+0000] {batch_filter.py:250} INFO - batch_slice: None was parsed to: slice(0, None, None)
[2025-04-06T18:44:01.126+0000] {logging_mixin.py:150} INFO - ‚úÖ Validator cr√©√©
[2025-04-06T18:44:01.129+0000] {logging_mixin.py:150} INFO - Aper√ßu des donn√©es:
[2025-04-06T18:44:01.197+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:44:01.198+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:44:01.318+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00,  8.32it/s]
[2025-04-06T18:44:01.319+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00,  8.32it/s]
[2025-04-06T18:44:01.320+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00,  8.32it/s]
[2025-04-06T18:44:01.321+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00,  8.32it/s]
[2025-04-06T18:44:01.322+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00,  8.07it/s]
[2025-04-06T18:44:01.422+0000] {logging_mixin.py:150} INFO -    id  id_employee      start_datetime  ... distance  activity_duration  comment
0   1        70643 2024-04-05 11:00:03  ...      NaN               3918     None
1   2        34382 2024-04-05 14:45:38  ...      NaN               5035     None
2   3        50316 2024-04-05 14:40:45  ...      NaN               3254     None
3   4        19773 2024-04-06 19:19:24  ...      NaN               5696     None
4   5        99401 2024-04-06 10:28:43  ...   6770.0               6449     None

[5 rows x 7 columns]
[2025-04-06T18:44:01.423+0000] {logging_mixin.py:150} INFO - Ajout des attentes...
[2025-04-06T18:44:01.444+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/expectations/expectation.py:1464: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  UserWarning,

[2025-04-06T18:44:01.473+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:44:01.474+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:44:01.494+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 99.32it/s]
[2025-04-06T18:44:01.499+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 78.63it/s]
[2025-04-06T18:44:01.506+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 125.80it/s]
[2025-04-06T18:44:01.510+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 111.83it/s]
[2025-04-06T18:44:01.514+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 124.42it/s]
[2025-04-06T18:44:01.518+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 114.08it/s]
[2025-04-06T18:44:01.533+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 117.82it/s]
[2025-04-06T18:44:01.536+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 111.95it/s]
[2025-04-06T18:44:01.542+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 116.78it/s]
[2025-04-06T18:44:01.545+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 113.07it/s]
[2025-04-06T18:44:01.546+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 110.48it/s]
[2025-04-06T18:44:01.547+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 108.89it/s]
[2025-04-06T18:44:01.574+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:44:01.575+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:44:01.584+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 223.54it/s]
[2025-04-06T18:44:01.589+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 137.57it/s]
[2025-04-06T18:44:01.592+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 226.63it/s]
[2025-04-06T18:44:01.598+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 174.37it/s]
[2025-04-06T18:44:01.600+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 198.84it/s]
[2025-04-06T18:44:01.605+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 166.73it/s]
[2025-04-06T18:44:01.609+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 206.06it/s]
[2025-04-06T18:44:01.612+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 190.88it/s]
[2025-04-06T18:44:01.616+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 194.05it/s]
[2025-04-06T18:44:01.619+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 182.24it/s]
[2025-04-06T18:44:01.620+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 177.92it/s]
[2025-04-06T18:44:01.621+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 174.04it/s]
[2025-04-06T18:44:01.664+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:44:01.665+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:44:01.671+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 338.43it/s]
[2025-04-06T18:44:01.683+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 116.14it/s]
[2025-04-06T18:44:01.686+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 190.54it/s]
[2025-04-06T18:44:01.698+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 122.97it/s]
[2025-04-06T18:44:01.756+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 65.83it/s] 
[2025-04-06T18:44:01.767+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.768+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.775+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.781+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.788+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.793+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.794+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 59.01it/s]
[2025-04-06T18:44:01.794+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 85.18it/s]
[2025-04-06T18:44:01.839+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:44:01.840+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:44:01.846+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 353.67it/s]
[2025-04-06T18:44:01.854+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 144.91it/s]
[2025-04-06T18:44:01.857+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 237.80it/s]
[2025-04-06T18:44:01.867+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 148.13it/s]
[2025-04-06T18:44:01.870+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 199.74it/s]
[2025-04-06T18:44:01.878+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 159.25it/s]
[2025-04-06T18:44:01.884+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 205.42it/s]
[2025-04-06T18:44:01.890+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 181.44it/s]
[2025-04-06T18:44:01.897+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 194.36it/s]
[2025-04-06T18:44:01.901+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 179.39it/s]
[2025-04-06T18:44:01.902+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 176.39it/s]
[2025-04-06T18:44:01.903+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 174.05it/s]
[2025-04-06T18:44:01.911+0000] {logging_mixin.py:150} INFO - ‚úÖ Attentes ajout√©es
[2025-04-06T18:44:01.912+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:44:01.913+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:44:01.920+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:44:01.922+0000] {logging_mixin.py:150} INFO - Cr√©ation du checkpoint...
[2025-04-06T18:44:01.923+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:44:01.924+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:44:01.932+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:44:01.935+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation...
[2025-04-06T18:44:01.936+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation avec SimpleCheckpoint...
[2025-04-06T18:44:01.942+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 51, in _get
    return self._store[key]
KeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 145, in get_checkpoint
    checkpoint_config: Optional[Any] = self.get(key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 188, in get
    value = self._store_backend.get(self.key_to_tuple(key))
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 121, in get
    value = self._get(key, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 53, in _get
    raise InvalidKeyError(f"{str(e)}")
great_expectations.exceptions.exceptions.InvalidKeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_validation_dag.py", line 351, in run_ge_validation
    run_name="airflow_validation_run"
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2288, in run_checkpoint
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2313, in _run_checkpoint
    id=id,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2163, in get_checkpoint
    name=name, id=id
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 151, in get_checkpoint
    message=f'Non-existent Checkpoint configuration named "{key.configuration_key}".\n\nDetails: {exc_ik}'  # type: ignore[union-attr]
great_expectations.exceptions.exceptions.CheckpointNotFoundError: Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',)
[2025-04-06T18:44:01.966+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=great_expectations_validation, task_id=validate_data, execution_date=20250406T184141, start_date=20250406T184400, end_date=20250406T184401
[2025-04-06T18:44:01.982+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 19 for task validate_data (Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',); 4360)
[2025-04-06T18:44:02.034+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-06T18:44:02.070+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
