[2025-04-06T18:46:08.645+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:46:08.666+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [queued]>
[2025-04-06T18:46:08.668+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 4
[2025-04-06T18:46:08.703+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_data> on 2025-04-06 18:41:41.055095+00:00
[2025-04-06T18:46:08.723+0000] {standard_task_runner.py:57} INFO - Started process 4459 to run task
[2025-04-06T18:46:08.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'great_expectations_validation', 'validate_data', 'manual__2025-04-06T18:41:41.055095+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_validation_dag.py', '--cfg-path', '/tmp/tmpz994jdfi']
[2025-04-06T18:46:08.737+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask validate_data
[2025-04-06T18:46:08.826+0000] {task_command.py:410} INFO - Running <TaskInstance: great_expectations_validation.validate_data manual__2025-04-06T18:41:41.055095+00:00 [running]> on host 6f966d9d4c8d
[2025-04-06T18:46:08.966+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='great_expectations_validation' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T18:41:41.055095+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T18:41:41.055095+00:00'
[2025-04-06T18:46:08.969+0000] {logging_mixin.py:150} INFO - üîç D√©marrage de la validation Great Expectations
[2025-04-06T18:46:08.970+0000] {logging_mixin.py:150} INFO - Connection string pour GE: postgresql://sportadvantagehr:sportpassword@business-postgres:5432/sportadvantages
[2025-04-06T18:46:08.974+0000] {util.py:2007} INFO - Could not find local context root directory
[2025-04-06T18:46:08.977+0000] {base.py:2134} INFO - Created temporary directory '/tmp/tmp6l3v0cy0' for ephemeral docs site
[2025-04-06T18:46:08.982+0000] {abstract_data_context.py:5575} INFO - EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`
[2025-04-06T18:46:08.983+0000] {config.py:185} INFO - Loading 'datasources' ->
[]
[2025-04-06T18:46:09.035+0000] {logging_mixin.py:150} INFO - ‚úÖ Contexte GE initialis√©
[2025-04-06T18:46:09.037+0000] {logging_mixin.py:150} INFO - Ajout de la source PostgreSQL...
[2025-04-06T18:46:09.145+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:46:09.192+0000] {logging_mixin.py:150} INFO - ‚úÖ Source PostgreSQL ajout√©e
[2025-04-06T18:46:09.193+0000] {logging_mixin.py:150} INFO - Connexion √† la base de donn√©es pour v√©rifier la table...
[2025-04-06T18:46:09.195+0000] {logging_mixin.py:150} INFO - Param√®tres de connexion GE: host=business-postgres, port=5432, user=sportadvantagehr, database=sportadvantages
[2025-04-06T18:46:09.211+0000] {logging_mixin.py:150} INFO - Sch√©mas disponibles: [('pg_toast',), ('pg_catalog',), ('public',), ('information_schema',), ('sport_advantages',), ('pg_temp_4',), ('pg_toast_temp_4',)]
[2025-04-06T18:46:09.212+0000] {logging_mixin.py:150} INFO - Le sch√©ma sport_advantages existe: True
[2025-04-06T18:46:09.216+0000] {logging_mixin.py:150} INFO - Tables dans le sch√©ma sport_advantages: [('employees',), ('commute_validations',), ('sport_activities',), ('sport_advantages',), ('employees_masked',)]
[2025-04-06T18:46:09.219+0000] {logging_mixin.py:150} INFO - La table sport_activities existe: True
[2025-04-06T18:46:09.227+0000] {logging_mixin.py:150} INFO - Colonnes de la table: [('id', 'integer'), ('id_employee', 'integer'), ('start_datetime', 'timestamp without time zone'), ('sport_type', 'character varying'), ('distance', 'integer'), ('activity_duration', 'integer'), ('comment', 'character varying')]
[2025-04-06T18:46:09.231+0000] {logging_mixin.py:150} INFO - Nombre de lignes dans la table: 2907
[2025-04-06T18:46:09.234+0000] {logging_mixin.py:150} INFO - √âchantillon de donn√©es: [(1, 70643, datetime.datetime(2024, 4, 5, 11, 0, 3), '√âquitation', None, 3918, None), (2, 34382, datetime.datetime(2024, 4, 5, 14, 45, 38), 'Musculation', None, 5035, None), (3, 50316, datetime.datetime(2024, 4, 5, 14, 40, 45), 'Judo', None, 3254, None), (4, 19773, datetime.datetime(2024, 4, 6, 19, 19, 24), 'Corde √† sauter', None, 5696, None), (5, 99401, datetime.datetime(2024, 4, 6, 10, 28, 43), 'Randonn√©e', 6770, 6449, None)]
[2025-04-06T18:46:09.236+0000] {logging_mixin.py:150} INFO - Ajout de l'asset de table...
[2025-04-06T18:46:09.267+0000] {logging_mixin.py:150} INFO - ‚úÖ Asset de table ajout√© avec succ√®s
[2025-04-06T18:46:09.269+0000] {logging_mixin.py:150} INFO - Construction de la requ√™te batch...
[2025-04-06T18:46:09.270+0000] {logging_mixin.py:150} INFO - ‚úÖ Requ√™te batch construite
[2025-04-06T18:46:09.273+0000] {logging_mixin.py:150} INFO - Configuration de la suite d'attente...
[2025-04-06T18:46:09.292+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente configur√©e
[2025-04-06T18:46:09.294+0000] {logging_mixin.py:150} INFO - Cr√©ation du validator...
[2025-04-06T18:46:09.308+0000] {fluent_base_model.py:257} INFO - PostgresDatasource.dict() - substituting config values
[2025-04-06T18:46:09.360+0000] {batch_filter.py:250} INFO - batch_slice: None was parsed to: slice(0, None, None)
[2025-04-06T18:46:09.369+0000] {logging_mixin.py:150} INFO - ‚úÖ Validator cr√©√©
[2025-04-06T18:46:09.372+0000] {logging_mixin.py:150} INFO - Aper√ßu des donn√©es:
[2025-04-06T18:46:09.387+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:46:09.388+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-04-06T18:46:09.411+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 45.11it/s]
[2025-04-06T18:46:09.414+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 38.91it/s]
[2025-04-06T18:46:09.416+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 36.44it/s]
[2025-04-06T18:46:09.418+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 1/1 [00:00<00:00, 34.48it/s]
[2025-04-06T18:46:09.442+0000] {logging_mixin.py:150} INFO -    id  id_employee      start_datetime  ... distance  activity_duration  comment
0   1        70643 2024-04-05 11:00:03  ...      NaN               3918     None
1   2        34382 2024-04-05 14:45:38  ...      NaN               5035     None
2   3        50316 2024-04-05 14:40:45  ...      NaN               3254     None
3   4        19773 2024-04-06 19:19:24  ...      NaN               5696     None
4   5        99401 2024-04-06 10:28:43  ...   6770.0               6449     None

[5 rows x 7 columns]
[2025-04-06T18:46:09.444+0000] {logging_mixin.py:150} INFO - Ajout des attentes...
[2025-04-06T18:46:09.448+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/great_expectations/expectations/expectation.py:1464: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  UserWarning,

[2025-04-06T18:46:09.478+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:46:09.482+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:46:09.503+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 93.26it/s]
[2025-04-06T18:46:09.511+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 67.44it/s]
[2025-04-06T18:46:09.524+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 94.90it/s]
[2025-04-06T18:46:09.536+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 73.76it/s]
[2025-04-06T18:46:09.540+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 85.85it/s]
[2025-04-06T18:46:09.545+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 78.25it/s]
[2025-04-06T18:46:09.553+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 97.80it/s]
[2025-04-06T18:46:09.557+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 92.34it/s]
[2025-04-06T18:46:09.562+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 98.76it/s]
[2025-04-06T18:46:09.566+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 94.79it/s]
[2025-04-06T18:46:09.567+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 93.49it/s]
[2025-04-06T18:46:09.568+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 92.30it/s]
[2025-04-06T18:46:09.597+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:46:09.599+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-06T18:46:09.606+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 286.54it/s]
[2025-04-06T18:46:09.612+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 149.74it/s]
[2025-04-06T18:46:09.616+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 227.84it/s]
[2025-04-06T18:46:09.622+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  50%|#####     | 4/8 [00:00<00:00, 173.93it/s]
[2025-04-06T18:46:09.624+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 198.93it/s]
[2025-04-06T18:46:09.629+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 165.03it/s]
[2025-04-06T18:46:09.635+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 191.80it/s]
[2025-04-06T18:46:09.639+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  88%|########7 | 7/8 [00:00<00:00, 174.14it/s]
[2025-04-06T18:46:09.644+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 178.01it/s]
[2025-04-06T18:46:09.647+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 165.57it/s]
[2025-04-06T18:46:09.648+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 161.03it/s]
[2025-04-06T18:46:09.650+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 156.81it/s]
[2025-04-06T18:46:09.698+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:46:09.699+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:46:09.706+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 285.56it/s]
[2025-04-06T18:46:09.719+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 102.70it/s]
[2025-04-06T18:46:09.723+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 171.59it/s]
[2025-04-06T18:46:09.736+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 107.95it/s]
[2025-04-06T18:46:09.740+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 147.15it/s]
[2025-04-06T18:46:09.752+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 114.52it/s]
[2025-04-06T18:46:09.760+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 148.55it/s]
[2025-04-06T18:46:09.766+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 134.39it/s]
[2025-04-06T18:46:09.774+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 147.96it/s]
[2025-04-06T18:46:09.779+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 137.48it/s]
[2025-04-06T18:46:09.781+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 134.12it/s]
[2025-04-06T18:46:09.783+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 132.10it/s]
[2025-04-06T18:46:09.842+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:46:09.843+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:   0%|          | 0/11 [00:00<?, ?it/s]
[2025-04-06T18:46:09.853+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 204.14it/s]
[2025-04-06T18:46:09.865+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  18%|#8        | 2/11 [00:00<00:00, 93.93it/s] 
[2025-04-06T18:46:09.869+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 155.85it/s]
[2025-04-06T18:46:09.882+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  36%|###6      | 4/11 [00:00<00:00, 105.00it/s]
[2025-04-06T18:46:09.886+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 138.97it/s]
[2025-04-06T18:46:09.895+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  55%|#####4    | 6/11 [00:00<00:00, 115.51it/s]
[2025-04-06T18:46:09.903+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 151.23it/s]
[2025-04-06T18:46:09.909+0000] {logging_mixin.py:150} WARNING - Calculating Metrics:  82%|########1 | 9/11 [00:00<00:00, 136.64it/s]
[2025-04-06T18:46:09.917+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 148.50it/s]
[2025-04-06T18:46:09.922+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 139.93it/s]
[2025-04-06T18:46:09.923+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 138.15it/s]
[2025-04-06T18:46:09.924+0000] {logging_mixin.py:150} WARNING - Calculating Metrics: 100%|##########| 11/11 [00:00<00:00, 136.49it/s]
[2025-04-06T18:46:09.932+0000] {logging_mixin.py:150} INFO - ‚úÖ Attentes ajout√©es
[2025-04-06T18:46:09.933+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:46:09.935+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:46:09.943+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:46:09.946+0000] {logging_mixin.py:150} INFO - Cr√©ation du checkpoint...
[2025-04-06T18:46:09.949+0000] {logging_mixin.py:150} INFO - Sauvegarde de la suite d'attente...
[2025-04-06T18:46:09.951+0000] {validator.py:1443} INFO - 	4 expectation(s) included in expectation_suite.
[2025-04-06T18:46:09.961+0000] {logging_mixin.py:150} INFO - ‚úÖ Suite d'attente sauvegard√©e
[2025-04-06T18:46:09.964+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation...
[2025-04-06T18:46:09.965+0000] {logging_mixin.py:150} INFO - Ex√©cution de la validation avec SimpleCheckpoint...
[2025-04-06T18:46:09.973+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 51, in _get
    return self._store[key]
KeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 145, in get_checkpoint
    checkpoint_config: Optional[Any] = self.get(key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/store.py", line 188, in get
    value = self._store_backend.get(self.key_to_tuple(key))
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/_store_backend.py", line 121, in get
    value = self._get(key, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/in_memory_store_backend.py", line 53, in _get
    raise InvalidKeyError(f"{str(e)}")
great_expectations.exceptions.exceptions.InvalidKeyError: ('sport_activities_checkpoint',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_validation_dag.py", line 351, in run_ge_validation
    run_name="airflow_validation_run"
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 318, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2288, in run_checkpoint
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2313, in _run_checkpoint
    id=id,
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2163, in get_checkpoint
    name=name, id=id
  File "/home/airflow/.local/lib/python3.7/site-packages/great_expectations/data_context/store/checkpoint_store.py", line 151, in get_checkpoint
    message=f'Non-existent Checkpoint configuration named "{key.configuration_key}".\n\nDetails: {exc_ik}'  # type: ignore[union-attr]
great_expectations.exceptions.exceptions.CheckpointNotFoundError: Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',)
[2025-04-06T18:46:10.000+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=great_expectations_validation, task_id=validate_data, execution_date=20250406T184141, start_date=20250406T184608, end_date=20250406T184609
[2025-04-06T18:46:10.017+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task validate_data (Non-existent Checkpoint configuration named "sport_activities_checkpoint".

Details: ('sport_activities_checkpoint',); 4459)
[2025-04-06T18:46:10.041+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-06T18:46:10.075+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
